name: GitHub_Action_Multplejobs_Demo
run-name: ${{ github.actor  }} is testing GitHub Action features 🚀
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Installing cowsay program
          run: sudo apt-get install cowsay -y
        - name: Executing cowsay command
          run: cowsay 'Installation Successfull' 
        - name: Writing cowsay command output to a file  
          run: cowsay 'Installation Successfull' >> cowsay.txt
        - name: Upload artifactory
          uses: actions/upload-artifact@v4
          with:
            name: cowsay
            path: cowsay.txt


    test:
        needs: [build]
        runs-on: ubuntu-latest
        steps:

        - name: Download the artifact
          uses: actions/download-artifact@v4
          with:
            name: cowsay
            path: cowsay.txt
        - name: Checking if cowsay output file exist
          run: ls -lrth cowsay.txt            
    deploy:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - name: Downloading the artifacts
              uses: actions/download-artifact@v4
              with:
                name: cowsay
                path: cowsay.txt
            - name: List the artifactory
              run: ls -lrth 
            - name: Changing to directory
              run: cd cowsay.txt   
            - name: Read the output file
              run:  cat cowsay.txt